project:
  type: website
  output-dir: docs

# Meta
description-meta: "Open Course on Energy and Climate Policy developed by Dr. Gang He, covering energy policy, climate policy, energy and climate policy."
author-meta: "Gang He"

website:
  title: "Energy and Climate Policy"
  description: "Open Course on Energy and Climate Policy developed by Dr. Gang He."
  navbar:
    background: light
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: 2025/schedule.qmd
      - text: Lectures
        href: lectures.qmd
      - text: Guest Speakers
        href: http://drganghe.github.io/climate-guest-speakers
        target: _blank
      - text: Guide
        menu:                           
        - text: Policy Memo
          href: policymemo.qmd 
        - text: Resources
          href: resources.qmd                
      - text: Archive
        menu:
          - text: Fall 2024
            href: 2024/schedule.qmd         
          - text: Fall 2023
            href: 2023/schedule.qmd                    
      - text: Dr. Gang He
        href: http://drganghe.github.io
        target: _blank        
    right: 
      - icon: github
        href: https://github.com/drganghe/energy-climate-policy
  page-navigation: true
  page-footer: 
    center: "[Energy and Climate Policy](https://drganghe.github.io/energy-climate-policy) class taught by [Gang He](http://drganghe.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # left: "[Gang He](http://drganghe.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # right: 
    #   - icon: github
    #     href: https://github.com/drganghe/energy-climate-policy
    #   - icon: twitter 
    #     href: https://twitter.com/DrGangHe
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/drganghe/energy-climate-policy
  repo-actions: [edit, issue, source]
  open-graph: true
  twitter-card: true
  #  creator: "@DrGangHe"
  #  image: "/lectures/lecture2/images/boe-equations.png"
  site-url: "https://drganghe.github.io/energy-climate-policy"
  google-analytics:
    tracking-id: "G-GG4GM3TPXK"
    anonymize-ip: true

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'

execute: 
  freeze: auto

comments:
  hypothesis: false
  

